instance_class: F1
runtime: nodejs12
service: default

env_variables:
    NEXT_PUBLIC_APP_SERVER_URL: https://neutron-dot-restaurant-recommender-system.et.r.appspot.com

handlers:
  - url: /.*
    secure: always
    script: auto